// Generates the isometric illustrations used on the services, service and process pages.
// Every face is one solid colour (no blends). Run `npm run illustrations` after changing a scene;
// the output, src/components/illustrations/scenes.generated.js, is committed.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const out = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../src/components/illustrations/scenes.generated.js');
const fs_write = (scenes) => {
  const text = `// Generated by scripts/illustrations/generate.mjs. Do not edit by hand.\nexport const SCENES = ${JSON.stringify(scenes, null, 2)};\n`;
  fs.writeFileSync(out, text);
  console.log(`wrote ${Object.keys(scenes).length} scenes to ${path.relative(process.cwd(), out)}`);
};

// ---- flat isometric helpers: every face is a solid colour, no blends ----
const K = 26, C = Math.cos(Math.PI / 6), SN = 0.5;
const P = (x, y, z) => [(x - y) * C * K, (x + y) * SN * K - z * K];
let box_ = null; // bounds of the scene being built
const track = (a) => a.forEach(([x, y, z]) => { const [px, py] = P(x, y, z); box_.x0 = Math.min(box_.x0, px); box_.x1 = Math.max(box_.x1, px); box_.y0 = Math.min(box_.y0, py); box_.y1 = Math.max(box_.y1, py); });
const pts = (a) => { track(a); return a.map(([x, y, z]) => P(x, y, z).map((n) => n.toFixed(1)).join(',')).join(' '); };
const cl = (c) => c.split(' ').map((x) => `il-${x}`).join(' ');
const poly = (a, cls) => `<polygon class="${cl(cls)}" points="${pts(a)}"/>`;
const T = { soft: ['t0', 'l0', 'r0'], white: ['tw', 'lw', 'rw'], prim: ['tp', 'lp', 'rp'], acc: ['ta', 'la', 'ra'], mid: ['tm', 'lm', 'rm'] };
// painter order: the nearest corner decides, height counts a little; decals share their parent's key
const keyOf = (x, y, z, w, d) => x + w + y + d + z * 0.6;
function box(x, y, z, w, d, h, tone = 'white') {
  const [t, l, r] = T[tone];
  return { x, y, z, w, d, h, key: keyOf(x, y, z, w, d), svg: () =>
    poly([[x, y + d, z], [x + w, y + d, z], [x + w, y + d, z + h], [x, y + d, z + h]], l) +
    poly([[x + w, y, z], [x + w, y + d, z], [x + w, y + d, z + h], [x + w, y, z + h]], r) +
    poly([[x, y, z + h], [x + w, y, z + h], [x + w, y + d, z + h], [x, y + d, z + h]], t) };
}
const onTop = (b, dx, dy, w, d, cls) => ({ key: b.key + 0.01, svg: () => poly([[b.x + dx, b.y + dy, b.z + b.h], [b.x + dx + w, b.y + dy, b.z + b.h], [b.x + dx + w, b.y + dy + d, b.z + b.h], [b.x + dx, b.y + dy + d, b.z + b.h]], cls) });
const onFront = (b, dx, dz, w, h, cls) => ({ key: b.key + 0.01, svg: () => poly([[b.x + dx, b.y + b.d, b.z + dz], [b.x + dx + w, b.y + b.d, b.z + dz], [b.x + dx + w, b.y + b.d, b.z + dz + h], [b.x + dx, b.y + b.d, b.z + dz + h]], cls) });
const flat = (x, y, z, w, d, cls, key = -0.5) => ({ key, svg: () => poly([[x, y, z], [x + w, y, z], [x + w, y + d, z], [x, y + d, z]], cls) });
const shadowOf = (b) => ({ key: -3, svg: () => poly([[b.x + 0.3, b.y + 0.3, 0.01], [b.x + b.w + 0.5, b.y + 0.3, 0.01], [b.x + b.w + 0.5, b.y + b.d + 0.5, 0.01], [b.x + 0.3, b.y + b.d + 0.5, 0.01]], 'sh') });
const dot = (x, y, z, r, cls) => ({ key: 900 + x + y, svg: () => { const [px, py] = P(x, y, z); track([[x, y, z + r / K]]); return `<circle class="${cl(cls)}" cx="${px.toFixed(1)}" cy="${py.toFixed(1)}" r="${r}"/>`; } });
const build = (items) => { box_ = { x0: 1e9, x1: -1e9, y0: 1e9, y1: -1e9 }; const body = [...items].sort((a, b) => a.key - b.key).map((i) => i.svg()).join(''); const pad = 14; return { viewBox: `${(box_.x0 - pad).toFixed(0)} ${(box_.y0 - pad).toFixed(0)} ${(box_.x1 - box_.x0 + 2 * pad).toFixed(0)} ${(box_.y1 - box_.y0 + 2 * pad).toFixed(0)}`, body }; };
const base = (w, d) => { const b = box(0, 0, 0, w, d, 0.5, 'soft'); b.key = -2; return [shadowOf(b), b]; };

const scenes = {};
// ERP: a hub and four modules on one platform, joined by flat paths
{ const I = [...base(9, 9)];
  I.push(flat(4.3, 1, 0.5, 0.4, 3.2, 'pl'), flat(4.3, 5, 0.5, 0.4, 3.2, 'pl'), flat(1, 4.3, 0.5, 3.2, 0.4, 'pl'), flat(5, 4.3, 0.5, 3.2, 0.4, 'pl'));
  const hub = box(3.5, 3.5, 0.5, 2, 2, 3.4, 'prim'); I.push(hub, onTop(hub, 0.3, 0.3, 1.4, 0.3, 'bw'), onTop(hub, 0.3, 0.9, 0.9, 0.3, 'bs'), onTop(hub, 0.3, 1.4, 1.1, 0.25, 'bs'));
  [[0.8, 0.8, 1.4, 'bp'], [5.9, 0.8, 2.2, 'ba'], [0.8, 5.9, 1.9, 'ba'], [5.9, 5.9, 1.1, 'bp']].forEach(([x, y, h, c]) => { const m = box(x, y, 0.5, 2.4, 2.4, h, 'white'); I.push(m, onTop(m, 0.4, 0.5, 1.5, 0.3, c), onTop(m, 0.4, 1.1, 1.1, 0.3, 'bs')); });
  scenes.erp = build(I); }
// CRM: three lanes of cards, one lifted out of its lane
{ const I = [...base(9.5, 8)];
  I.push(flat(3.2, 0.5, 0.5, 0.12, 7, 'pl'), flat(6.4, 0.5, 0.5, 0.12, 7, 'pl'));
  const card = (x, y, z, tone, bar, lift) => { const c = box(x, y, z, 2.2, 1.5, 0.28, tone); const o = [c, onTop(c, 0.3, 0.35, 1.0, 0.25, tone === 'prim' ? 'bw' : bar), onTop(c, 0.3, 0.8, 1.5, 0.22, tone === 'prim' ? 'bw' : 'bs'), dot(x + 1.9, y + 0.7, z + 0.28, 4.5, bar === 'ba' ? 'da' : 'dp')]; if (lift) o.unshift({ key: -0.9, svg: () => poly([[x + 0.3, y + 0.3, 0.51], [x + 2.5, y + 0.3, 0.51], [x + 2.5, y + 1.8, 0.51], [x + 0.3, y + 1.8, 0.51]], 'sh') }); return o; };
  [[0.5, 0.8, 0.5, 'white', 'bp'], [0.5, 2.6, 0.5, 'white', 'ba'], [0.5, 4.4, 0.5, 'white', 'bp'], [3.6, 0.8, 0.5, 'white', 'bp'], [3.6, 2.6, 1.9, 'prim', 'bw', true], [6.8, 0.8, 0.5, 'white', 'ba'], [6.8, 2.6, 0.5, 'white', 'bp']].forEach((a) => I.push(...card(...a)));
  scenes.crm = build(I); }
// Mobile: a standing phone with floating cards
{ const I = [...base(8, 6)];
  const ph = box(3.2, 2.2, 0.5, 2.4, 0.5, 5, 'mid'); I.push(ph, onFront(ph, 0.2, 0.3, 2.0, 4.4, 'scr'), onFront(ph, 0.5, 4.3, 1.4, 0.3, 'bp'), onFront(ph, 0.5, 3.5, 1.4, 0.3, 'bs'), onFront(ph, 0.5, 3.0, 1.0, 0.25, 'bs'), onFront(ph, 0.5, 2.2, 1.4, 0.3, 'ba'), onFront(ph, 0.5, 1.7, 1.0, 0.25, 'bs'), onFront(ph, 0.5, 0.7, 1.4, 0.3, 'bp'));
  [[0.2, 1.2, 2.4, 'white', 'bp'], [6.0, 1.0, 3.4, 'white', 'ba'], [6.2, 3.6, 1.5, 'acc', 'bw']].forEach(([x, y, z, tone, c]) => { const f = box(x, y, z, 1.9, 1.3, 0.3, tone); I.push({ key: -0.9, svg: () => poly([[x + 0.3, y + 0.3, 0.51], [x + 2.2, y + 0.3, 0.51], [x + 2.2, y + 1.6, 0.51], [x + 0.3, y + 1.6, 0.51]], 'sh') }, f, onTop(f, 0.3, 0.3, 1.0, 0.25, c), onTop(f, 0.3, 0.75, 1.3, 0.2, tone === 'acc' ? 'bw' : 'bs')); });
  I.push(dot(0.7, 4.6, 0.9, 5, 'da'));
  scenes.mobile = build(I); }
// Web and search: a browser slab and a search bar card in front
{ const I = [...base(9, 7)];
  const br = box(0.8, 1.0, 0.5, 6.4, 0.4, 4.6, 'white'); I.push(br, onFront(br, 0, 3.9, 6.4, 0.7, 'hd'), onFront(br, 0.3, 4.1, 0.0, 0.0, 'bs'), dot(1.1, 1.4, 4.9, 3.5, 'dp'), dot(1.6, 1.4, 5.1, 3.5, 'da'), dot(2.1, 1.4, 5.3, 3.5, 'dm'),
    onFront(br, 0.5, 3.1, 3.2, 0.4, 'bp'), onFront(br, 0.5, 2.4, 4.6, 0.25, 'bs'), onFront(br, 0.5, 1.9, 3.8, 0.25, 'bs'), onFront(br, 0.5, 0.8, 1.7, 0.6, 'ba'), onFront(br, 4.2, 0.7, 1.9, 2.0, 'bm'));
  const sb = box(2.8, 4.0, 0.5, 5.6, 0.6, 1.2, 'prim'); I.push(shadowOf(sb), sb, onFront(sb, 0.4, 0.4, 0.5, 0.5, 'bw'), onFront(sb, 1.2, 0.5, 3.6, 0.25, 'bw'));
  scenes.web = build(I); }
// Ads: a stepped target with items flowing in
{ const I = [...base(9, 9)];
  [[0.8, 7.4, 0.5, 'soft'], [1.9, 5.2, 1.2, 'mid'], [3.0, 3.0, 1.9, 'white']].forEach(([o, w, z, t]) => { const b = box(o, o, z, w, w, 0.7, t); b.key = 20 + z * 10; I.push(shadowOf({ x: o, y: o, w, d: w }), b); });
  const tgt = box(3.7, 3.7, 2.6, 1.6, 1.6, 0.5, 'acc'); tgt.key = 20 + 2.6 * 10; I.push(tgt, onTop(tgt, 0.4, 0.5, 0.8, 0.25, 'bw'));
  [[1.2, 1.2, 1.9, 'dp'], [7.2, 1.4, 1.9, 'da'], [1.5, 7.2, 1.9, 'da'], [7.0, 7.0, 1.9, 'dp'], [4.5, 0.9, 1.9, 'dp'], [0.9, 4.5, 1.9, 'da']].forEach(([x, y, z, c]) => I.push(dot(x, y, z, 6, c)));
  [[2.4, 2.4, 3.2, 'dp'], [6.2, 2.5, 3.0, 'da'], [2.5, 6.3, 3.0, 'da']].forEach(([x, y, z, c]) => I.push(dot(x, y, z, 5, c)));
  scenes.ads = build(I); }
// Automation: three nodes joined by pipes, a cube on its way
{ const I = [...base(10, 7)];
  [[2.4, 2.8, 2.2, 0.6], [4.6, 2.8, 1.4, 0.6], [6.0, 1.4, 0.6, 1.6], [6.0, 4.0, 0.6, 1.6]].forEach(([x, y, w, d]) => I.push(box(x, y, 0.5, w, d, 0.3, 'mid')));
  const n1 = box(0.6, 2.2, 0.5, 1.8, 1.8, 1.6, 'acc'); I.push(n1, onTop(n1, 0.3, 0.6, 1.2, 0.3, 'bw'));
  const n2 = box(4.6, 2.2, 0.5, 1.8, 1.8, 2.4, 'prim'); I.push(n2, onTop(n2, 0.3, 0.5, 1.2, 0.3, 'bw'), onTop(n2, 0.3, 1.0, 0.8, 0.25, 'bs'));
  const n3 = box(6.8, 0.4, 0.5, 2.6, 1.6, 1.2, 'white'); I.push(n3, onTop(n3, 0.3, 0.4, 1.4, 0.3, 'bp'));
  const n4 = box(6.8, 4.8, 0.5, 2.6, 1.6, 1.2, 'white'); I.push(n4, onTop(n4, 0.3, 0.4, 1.4, 0.3, 'ba'));
  I.push(box(2.8, 2.9, 0.8, 0.9, 0.4, 0.8, 'acc'));
  scenes.automation = build(I); }


// Idea to product: steps climbing from a first idea to a finished product
{ const I = [...base(10, 6)];
  [[0.6, 0.6, 0.5, 2.0], [2.8, 0.6, 0.5, 3.0], [5.0, 0.6, 0.5, 4.0]].forEach(([x, y, z, h], i) => { const s = box(x, y, z, 2.0, 4.4, h * 0.45, i === 2 ? 'prim' : 'white'); I.push(shadowOf(s), s, onTop(s, 0.3, 0.6, 1.4, 0.3, i === 2 ? 'bw' : 'bs'), onTop(s, 0.3, 1.2, 0.9, 0.25, i === 2 ? 'bw' : i === 1 ? 'ba' : 'bp')); });
  const tgt = box(7.2, 1.2, 0.5, 2.0, 3.0, 2.6, 'acc'); I.push(shadowOf(tgt), tgt, onTop(tgt, 0.3, 0.5, 1.4, 0.3, 'bw'), onTop(tgt, 0.3, 1.1, 0.9, 0.25, 'bw'));
  I.push(dot(1.6, 0.9, 2.6, 7, 'da'), dot(3.8, 1.4, 3.2, 5, 'dp'), dot(6.0, 1.1, 3.9, 4, 'da'));
  scenes.idea = build(I); }
// Software engineering: layered architecture, each layer a slab with its own modules
{ const I = [...base(8, 8)];
  [[0.5, 'white'], [1.9, 'mid'], [3.3, 'prim']].forEach(([z, t], i) => { const l = box(1, 1, z, 6, 6, 0.5, t); l.key = 20 + z * 10; I.push(shadowOf({ x: 1, y: 1, w: 6, d: 6 }), l);
    const o = (dx, dy, w, c) => { const m = box(1 + dx, 1 + dy, z + 0.5, w, 1.4, 0.5, i === 2 ? 'white' : 'soft'); m.key = 20 + z * 10 + 1 + dx * 0.01; I.push(m, { key: m.key + 0.01, svg: () => onTop(m, 0.2, 0.3, w - 0.5, 0.25, c).svg() }); };
    o(0.6, 0.8, 1.6, i === 1 ? 'ba' : 'bp'); o(3.0, 0.8, 1.6, 'bp'); o(0.6, 3.6, 1.6, 'bp'); o(3.0, 3.6, 1.6, i === 0 ? 'ba' : 'bp'); });
  I.push(dot(4, 0.2, 4.3, 5, 'da'), dot(0.2, 4, 4.3, 5, 'dp'));
  scenes.engineering = build(I); }
// SEO: a stack of result pages with the first one lifted, and a search bar in front
{ const I = [...base(9, 8)];
  [[0.5, 'white', 'bs', 0], [1.5, 'white', 'bs', 1], [2.5, 'acc', 'bw', 2]].forEach(([z, t, c, i]) => { const pg = box(1.4, 0.8, z, 4.6, 3.4, 0.3, t); pg.key = 20 + z * 10; I.push(shadowOf({ x: 1.4, y: 0.8, w: 4.6, d: 3.4 }), pg, { key: pg.key + 0.01, svg: () => onTop(pg, 0.4, 0.4, 2.2, 0.35, i === 2 ? 'bw' : 'bp').svg() }, { key: pg.key + 0.02, svg: () => onTop(pg, 0.4, 1.1, 3.6, 0.22, c).svg() }, { key: pg.key + 0.03, svg: () => onTop(pg, 0.4, 1.6, 2.8, 0.22, c).svg() }); });
  const sb = box(3.0, 5.0, 0.5, 5.4, 0.7, 1.1, 'prim'); I.push(shadowOf(sb), sb, onFront(sb, 0.4, 0.35, 0.5, 0.5, 'bw'), onFront(sb, 1.2, 0.45, 3.5, 0.25, 'bw'));
  I.push(dot(7.3, 1.4, 1.5, 6, 'da'), dot(7.9, 2.8, 1.9, 4, 'dp'));
  scenes.seo = build(I); }
// Content and social: a feed of post cards, some with a picture, one highlighted
{ const I = [...base(9.5, 8)];
  const post = (x, y, z, tone, pic) => { const c = box(x, y, z, 2.6, 1.9, 0.3, tone); return [c, onTop(c, 0.25, 0.25, 2.1, 0.8, pic), onTop(c, 0.25, 1.2, 1.4, 0.2, tone === 'prim' ? 'bw' : 'bs'), dot(x + 2.2, y + 1.5, z + 0.3, 4, tone === 'prim' ? 'da' : 'dp')]; };
  [[0.6, 0.6, 0.5, 'white', 'bm'], [3.6, 0.6, 0.5, 'white', 'ba'], [6.5, 0.6, 0.5, 'white', 'bm'], [0.6, 3.0, 0.5, 'white', 'bp'], [3.6, 3.0, 1.6, 'prim', 'bw'], [6.5, 3.0, 0.5, 'white', 'bm'], [2.0, 5.5, 0.5, 'white', 'ba'], [5.2, 5.5, 0.5, 'white', 'bm']].forEach(([x, y, z, t, p]) => { if (z > 1) I.push({ key: -0.9, svg: () => poly([[x + 0.3, y + 0.3, 0.51], [x + 2.9, y + 0.3, 0.51], [x + 2.9, y + 2.2, 0.51], [x + 0.3, y + 2.2, 0.51]], 'sh') }); I.push(...post(x, y, z, t, p)); });
  scenes.content = build(I); }

// About: a studio, four desks with screens around one shared table
{ const I = [...base(10, 8)];
  const tb = box(3.4, 2.8, 0.5, 3.2, 2.4, 0.5, 'prim'); I.push(shadowOf(tb), tb, onTop(tb, 0.4, 0.5, 1.6, 0.3, 'bw'), onTop(tb, 0.4, 1.2, 1.0, 0.25, 'bw'));
  [[0.6, 0.6, 'bp'], [6.6, 0.6, 'ba'], [0.6, 5.4, 'ba'], [6.6, 5.4, 'bp']].forEach(([x, y, c]) => { const d = box(x, y, 0.5, 2.8, 1.8, 0.7, 'white'); I.push(shadowOf(d), d, onTop(d, 0.4, 0.3, 1.4, 0.3, 'bs'));
    const m = box(x + 0.9, y + 0.2, 1.2, 1.0, 0.2, 1.1, 'mid'); I.push(m, onFront(m, 0.1, 0.15, 0.8, 0.8, c)); });
  I.push(dot(4.2, 2.2, 1.6, 5, 'da'), dot(5.8, 6.0, 1.6, 5, 'dp'), dot(2.6, 4.2, 1.6, 4, 'dp'));
  scenes.about = build(I); }
// Contact: an envelope with a letter lifting out, and two chat cards beside it
{ const I = [...base(9.5, 8)];
  const env = box(1.2, 2.6, 0.5, 5.4, 3.6, 1.0, 'white'); I.push(shadowOf(env), env, onTop(env, 0.4, 0.4, 3.0, 0.3, 'bs'), onTop(env, 0.4, 1.0, 2.0, 0.3, 'bs'), onTop(env, 3.6, 2.2, 1.4, 0.9, 'bp'));
  const letter = box(2.0, 3.0, 1.5, 3.6, 2.2, 0.25, 'prim'); I.push({ key: letter.key - 0.4, svg: () => poly([[2.3, 3.3, 1.51], [5.9, 3.3, 1.51], [5.9, 5.5, 1.51], [2.3, 5.5, 1.51]], 'sh') }, letter, onTop(letter, 0.4, 0.4, 1.8, 0.3, 'bw'), onTop(letter, 0.4, 0.95, 2.4, 0.22, 'bw'), onTop(letter, 0.4, 1.45, 1.4, 0.22, 'bw'));
  [[6.6, 0.6, 2.6, 'white', 'bp'], [6.9, 5.4, 1.6, 'acc', 'bw']].forEach(([x, y, z, tone, c]) => { const f = box(x, y, z, 2.2, 1.4, 0.3, tone); I.push({ key: -0.9, svg: () => poly([[x + 0.3, y + 0.3, 0.51], [x + 2.5, y + 0.3, 0.51], [x + 2.5, y + 1.7, 0.51], [x + 0.3, y + 1.7, 0.51]], 'sh') }, f, onTop(f, 0.3, 0.3, 1.2, 0.25, c), onTop(f, 0.3, 0.8, 1.6, 0.2, tone === 'acc' ? 'bw' : 'bs')); });
  I.push(dot(0.8, 1.0, 1.8, 5, 'da'), dot(1.8, 0.6, 2.4, 4, 'dp'));
  scenes.contact = build(I); }
// Labs: a workbench with a QR block, a tall vessel and a small gear cube
{ const I = [...base(10, 6)];
  const qr = box(0.8, 1.0, 0.5, 3.6, 3.6, 0.5, 'white'); I.push(shadowOf(qr), qr);
  [[0.4, 0.4], [2.2, 0.4], [0.4, 2.2]].forEach(([dx, dy]) => I.push(onTop(qr, dx, dy, 1.0, 1.0, 'bp'), onTop(qr, dx + 0.3, dy + 0.3, 0.4, 0.4, 'bw')));
  [[1.6, 1.4, 0.4, 0.4], [2.6, 1.2, 0.4, 0.4], [1.4, 2.6, 0.4, 0.4], [2.4, 2.4, 0.4, 0.4], [3.0, 2.8, 0.3, 0.3], [1.9, 3.1, 0.3, 0.3]].forEach(([dx, dy, w, d]) => I.push(onTop(qr, dx, dy, w, d, 'bp')));
  const v = box(5.2, 1.2, 0.5, 1.8, 1.8, 3.4, 'acc'); I.push(shadowOf(v), v, onTop(v, 0.3, 0.4, 1.2, 0.3, 'bw'), onTop(v, 0.3, 1.0, 0.8, 0.25, 'bw'));
  const g = box(7.4, 2.8, 0.5, 1.6, 1.6, 1.4, 'prim'); I.push(shadowOf(g), g, onTop(g, 0.3, 0.3, 1.0, 0.3, 'bw'));
  I.push(dot(6.1, 0.8, 4.6, 6, 'da'), dot(8.2, 1.6, 2.8, 4, 'dp'), dot(4.6, 4.8, 1.4, 4, 'dp'));
  scenes.labs = build(I); }
// 404: a path that stops at a gap, a lone cube waiting on the near side
{ const I = [...base(8, 8)];
  const a = box(2.6, 0.7, 0.5, 2.8, 2.8, 0.4, 'white'); I.push(a, onTop(a, 1.0, 0.4, 0.8, 2.0, 'bs'));
  const b = box(2.6, 4.5, 0.5, 2.8, 2.8, 0.4, 'white'); I.push(b, onTop(b, 1.0, 0.4, 0.8, 2.0, 'bs'));
  const c = box(3.2, 1.3, 0.9, 1.6, 1.6, 1.8, 'acc'); I.push(shadowOf({ x: 3.2, y: 1.3, w: 1.6, d: 1.6 }), c, onTop(c, 0.3, 0.4, 1.0, 0.3, 'bw'));
  const sign = box(3.5, 5.4, 0.9, 0.5, 0.5, 3.4, 'prim'); I.push(shadowOf({ x: 3.5, y: 5.4, w: 0.5, d: 0.5 }), sign, onFront(sign, 0.08, 2.4, 0.34, 0.6, 'bw'), onFront(sign, 0.08, 1.5, 0.34, 0.4, 'bw'));
  const board = box(2.9, 5.2, 4.3, 1.7, 0.4, 0.9, 'acc'); I.push(board, onFront(board, 0.3, 0.3, 1.1, 0.3, 'bw'));
  I.push(dot(4.0, 3.9, 1.8, 6, 'dp'), dot(4.0, 3.9, 3.0, 4, 'da'), dot(0.9, 6.6, 1.8, 4, 'da'), dot(6.8, 1.4, 1.6, 4, 'dp'));
  scenes.notfound = build(I); }

fs_write(scenes);
