// Text that is specific to the intake form's layout. Intent titles and the
// confirmation screen come from content/conversionContent.js.
export const leadFormCopy = {
  en: {
    badge: "Project intake",
    stepLabel: ["Step 1 of 2: Primary info", "Step 2 of 2: Additional context (optional)"],
    stepHint: [
      "Only 3 quick fields to reserve your session.",
      "Helps us prepare a tailored architecture assessment.",
    ],
    fullName: "Full name",
    fullNamePlaceholder: "Your name",
    contact: "WhatsApp / work email",
    contactPlaceholder: "name@company.com or +971 5x xxx xxxx",
    need: "What you need",
    serviceOptions: {
      build: "Platform / SaaS / ERP build",
      audit: "System audit and review",
      infrastructure: "Growth infrastructure setup",
    },
    addDetails: "Add project details",
    submitDirect: "Submit directly",
    privacyNote: "We use your details only to reply to your request.",
    company: "Company / organization",
    companyPlaceholder: "Your company or project",
    description: "Current architecture or bottleneck",
    descriptionPlaceholder: "Briefly describe your goals, current bottlenecks, or technical scope...",
    optional: "(Optional)",
    back: "Back",
    confirm: "Confirm and submit",
    errors: {
      select: "Select an option",
      invalidEmail: "Please enter a valid work email or WhatsApp with country code.",
      invalidWebsite: "Please enter a valid website.",
      required: "This field is required.",
      submit: "We could not submit your request right now. Please try again or reach out directly.",
    },
  },
  ar: {
    badge: "استقبال المشاريع",
    stepLabel: ["الخطوة 1 من 2: المعلومات الأساسية", "الخطوة 2 من 2: تفاصيل إضافية (اختيارية)"],
    stepHint: [
      "3 حقول سريعة فقط لحجز موعدك.",
      "تساعدنا على خدمتك بشكل أفضل وتحديد نطاق العمل بدقة.",
    ],
    fullName: "الاسم الكامل",
    fullNamePlaceholder: "اسمك",
    contact: "واتساب / بريد العمل",
    contactPlaceholder: "name@company.com أو +966 5x xxx xxxx",
    need: "ما تحتاجه بالضبط",
    serviceOptions: {
      build: "بناء منصة / SaaS / ERP",
      audit: "تدقيق تقني للمنظومة الحالية",
      infrastructure: "بنية تحتية للنمو والتسويق",
    },
    addDetails: "المتابعة لإضافة تفاصيل",
    submitDirect: "إرسال الطلب الآن مباشرة",
    privacyNote: "نستخدم بياناتك فقط للرد على طلبك.",
    company: "اسم الشركة / المنظمة",
    companyPlaceholder: "اسم شركتك أو مشروعك",
    description: "تفاصيل المنظومة أو التحدي الحالي",
    descriptionPlaceholder: "صف باختصار ما ترغب في إنجازه، التحديات التقنية، أو المتطلبات الخاصة...",
    optional: "(اختياري)",
    back: "رجوع",
    confirm: "تأكيد وإرسال الطلب",
    errors: {
      select: "اختر ما يناسبك",
      invalidEmail: "يرجى إدخال بريد مهني صحيح أو رقم واتساب مع رمز الدولة.",
      invalidWebsite: "يرجى إدخال موقع صحيح.",
      required: "هذا الحقل مطلوب للمتابعة.",
      submit: "تعذر إرسال الطلب حالياً. يرجى المحاولة مرة أخرى أو مراسلتنا مباشرة.",
    },
  },
};
