// Text that is specific to the intake form's layout. Intent titles and the
// confirmation screen come from content/conversionContent.js.
export const leadFormCopy = {
  en: {
    badge: "Project intake",
    stepLabel: ["Step 1 of 2: Primary info", "Step 2 of 2: Additional context (optional)"],
    stepHint: [
      "Only 3 quick fields to reserve your session.",
      "Helps us prepare a tailored architecture assessment.",
    ],
    fullName: "Full name",
    fullNamePlaceholder: "Your name",
    contact: "WhatsApp / work email",
    contactPlaceholder: "name@company.com or +971 5x xxx xxxx",
    need: "What you need",
    serviceOptions: {
      build: "Build a platform, app, or business system",
      audit: "System audit and review",
      infrastructure: "Marketing, tracking, and growth setup",
    },
    addDetails: "Add project details",
    submitDirect: "Submit directly",
    privacyNote: "We use your details only to reply to your request.",
    company: "Company / organization",
    companyPlaceholder: "Your company or project",
    market: "Where are your customers?",
    marketPlaceholder: "Choose a market",
    notSpecified: "Not specified",
    marketOptions: {
      egypt: "Egypt",
      saudi: "Saudi Arabia",
      uae: "United Arab Emirates",
      "other-gulf": "Another Gulf country",
      other: "Somewhere else",
    },
    timeline: "When do you want to start?",
    timelinePlaceholder: "Choose a timeframe",
    timelineOptions: {
      now: "As soon as possible",
      quarter: "Within three months",
      exploring: "Just exploring",
    },
    description: "Current architecture or bottleneck",
    descriptionPlaceholder: "Briefly describe your goals, current bottlenecks, or technical scope...",
    optional: "(Optional)",
    back: "Back",
    confirm: "Confirm and submit",
    errors: {
      select: "Select an option",
      invalidEmail: "Please enter a valid work email or WhatsApp with country code.",
      invalidWebsite: "Please enter a valid website.",
      required: "This field is required.",
      submit: "We could not submit your request right now. Please try again or reach out directly.",
    },
  },
  ar: {
    badge: "استقبال المشاريع",
    stepLabel: ["الخطوة 1 من 2: المعلومات الأساسية", "الخطوة 2 من 2: تفاصيل إضافية (اختيارية)"],
    stepHint: [
      "3 حقول سريعة فقط لحجز موعدك.",
      "تساعدنا على خدمتك بشكل أفضل وتحديد نطاق العمل بدقة.",
    ],
    fullName: "الاسم الكامل",
    fullNamePlaceholder: "اسمك",
    contact: "واتساب / بريد العمل",
    contactPlaceholder: "name@company.com أو +966 5x xxx xxxx",
    need: "ما تحتاجه بالضبط",
    serviceOptions: {
      build: "بناء منصة أو تطبيق أو نظام أعمال",
      audit: "تدقيق تقني للمنظومة الحالية",
      infrastructure: "إعداد التسويق والتتبع والنمو",
    },
    addDetails: "المتابعة لإضافة تفاصيل",
    submitDirect: "إرسال الطلب الآن مباشرة",
    privacyNote: "نستخدم بياناتك فقط للرد على طلبك.",
    company: "اسم الشركة / المنظمة",
    companyPlaceholder: "اسم شركتك أو مشروعك",
    market: "أين عملاؤك؟",
    marketPlaceholder: "اختر السوق",
    notSpecified: "غير محدد",
    marketOptions: {
      egypt: "مصر",
      saudi: "السعودية",
      uae: "الإمارات",
      "other-gulf": "دولة خليجية أخرى",
      other: "مكان آخر",
    },
    timeline: "متى تريد أن تبدأ؟",
    timelinePlaceholder: "اختر الإطار الزمني",
    timelineOptions: {
      now: "في أقرب وقت",
      quarter: "خلال ثلاثة أشهر",
      exploring: "أستكشف فقط",
    },
    description: "تفاصيل المنظومة أو التحدي الحالي",
    descriptionPlaceholder: "صف باختصار ما ترغب في إنجازه، التحديات التقنية، أو المتطلبات الخاصة...",
    optional: "(اختياري)",
    back: "رجوع",
    confirm: "تأكيد وإرسال الطلب",
    errors: {
      select: "اختر ما يناسبك",
      invalidEmail: "يرجى إدخال بريد مهني صحيح أو رقم واتساب مع رمز الدولة.",
      invalidWebsite: "يرجى إدخال موقع صحيح.",
      required: "هذا الحقل مطلوب للمتابعة.",
      submit: "تعذر إرسال الطلب حالياً. يرجى المحاولة مرة أخرى أو مراسلتنا مباشرة.",
    },
  },
};
