// Copy for the service wave on the home page. Every line describes a service in
// general terms; nothing here promises a result, a price or a delivery time.

export const serviceWaveContent = {
  en: {
    title: 'What does your business need?',
    hint: 'Tap any service, or grab it and move it.',
    regionLabel: 'Our services',
    close: 'Close',
    modes: { order: 'Order it', explain: 'Explain it', consult: 'Consultation' },
    notePlaceholder: {
      order: 'Describe what you need in a sentence (optional)',
      explain: 'What would you like us to explain? (optional)',
      consult: 'What would you like to ask about? (optional)',
    },
    contactLabel: 'Phone number or email',
    contactError: 'Enter a valid phone number or email.',
    submit: 'Send',
    sending: 'Sending',
    submitError: 'We could not send it. Please try again or use the contact page.',
    successTitle: 'We got your request',
    successBody: 'We will review it and get back to you using the details you wrote.',
    privacy: 'By sending you agree that we contact you about this request.',
    privacyLink: 'Privacy policy',
    items: {
      erp: { label: 'ERP', text: 'A system that brings sales, stock and accounts into one place.' },
      crm: { label: 'CRM', text: 'Follow customers, opportunities and every conversation.' },
      odoo: { label: 'Odoo', text: 'Apps and solutions built on Odoo to fit how you work.' },
      project: { label: 'Your project', text: 'Tell us your idea and we start from there.' },
      websites: { label: 'Websites', text: 'A fast website that search engines can read.' },
      seo: { label: 'SEO', text: 'Better visibility in search and in AI answers.' },
      mobile: { label: 'Mobile apps', text: 'A mobile app in Arabic and English.' },
      ads: { label: 'Ads', text: 'Managing paid advertising campaigns.' },
      automation: { label: 'Automation', text: 'Less repeated manual work.' },
    },
  },
  ar: {
    title: 'ماذا تحتاج شركتك؟',
    hint: 'اضغط على أي خدمة، أو امسكها وحرّكها.',
    regionLabel: 'خدماتنا',
    close: 'إغلاق',
    modes: { order: 'اطلب الخدمة', explain: 'اشرحلي', consult: 'استشارة' },
    notePlaceholder: {
      order: 'اكتب طلبك في جملة (اختياري)',
      explain: 'ما الذي تريد أن نشرحه؟ (اختياري)',
      consult: 'ما موضوع استشارتك؟ (اختياري)',
    },
    contactLabel: 'رقم الموبايل أو الإيميل',
    contactError: 'اكتب رقم موبايل صحيحًا أو إيميلًا صحيحًا.',
    submit: 'أرسل',
    sending: 'جارٍ الإرسال',
    submitError: 'تعذّر الإرسال. حاول مرة أخرى أو استخدم صفحة التواصل.',
    successTitle: 'وصلنا طلبك',
    successBody: 'سنراجعه ونتواصل معك على البيانات التي كتبتها.',
    privacy: 'بإرسالك توافق على أن نتواصل معك بخصوص هذا الطلب.',
    privacyLink: 'سياسة الخصوصية',
    items: {
      erp: { label: 'ERP', text: 'نظام يجمع المبيعات والمخزون والحسابات في مكان واحد.' },
      crm: { label: 'CRM', text: 'متابعة العملاء والفرص وسجل كل تواصل.' },
      odoo: { label: 'Odoo', text: 'تطبيقات وحلول مبنية على Odoo حسب شغلك.' },
      project: { label: 'مشروعك', text: 'قل لنا فكرتك ونبدأ منها.' },
      websites: { label: 'مواقع', text: 'موقع سريع تقرؤه محركات البحث.' },
      seo: { label: 'SEO', text: 'ظهور أفضل في البحث وفي إجابات الذكاء الاصطناعي.' },
      mobile: { label: 'تطبيقات موبايل', text: 'تطبيق للموبايل بالعربية والإنجليزية.' },
      ads: { label: 'إعلانات', text: 'إدارة حملات إعلانية مدفوعة.' },
      automation: { label: 'أتمتة', text: 'تقليل الشغل اليدوي المتكرر.' },
    },
  },
};
