// Copy for the fifth batch of free tools: word and character counter, robots.txt and sitemap
// generator, and invoice generator. English and Arabic must keep the same shape (a test checks it).

const en = {
  hub: {
    wordcount: {
      title: 'Word and Character Counter',
      text: 'Count words, characters, sentences and reading time in Arabic or English, see the most used words, and check common length limits.',
    },
    seofiles: {
      title: 'Robots.txt and Sitemap Generator',
      text: 'Build a robots.txt and a sitemap.xml, check the rules, and test whether a crawler may open a path.',
    },
    invoice: {
      title: 'Invoice Generator',
      text: 'Make a clean invoice with VAT per line, then print it or save it as a PDF from your browser.',
    },
  },

  wordcount: {
    h1: 'Word and character counter',
    subtitle: 'Paste or type a text and the counts update as you go. It works for Arabic and English, and nothing leaves your browser.',
    textLabel: 'Your text',
    placeholder: 'Type or paste your text here…',
    stats: {
      words: 'Words',
      characters: 'Characters',
      charactersNoSpaces: 'Without spaces',
      sentences: 'Sentences',
      paragraphs: 'Paragraphs',
      reading: 'Reading time',
      speaking: 'Speaking time',
    },
    time: '{m} min {s} s',
    speedLabel: 'Reading speed',
    speeds: { slow: 'Slow', average: 'Average', fast: 'Fast' },
    speedNote: 'About {n} words a minute. Reading time is an estimate.',
    limits: {
      title: 'Limits',
      intro: 'Common length limits, as figures often quoted. Check the current rules of the place you publish.',
      names: { title: 'Page title', description: 'Meta description', sms: 'One SMS', x: 'X post', caption: 'Instagram caption' },
      left: '{n} left',
      over: '{n} over',
    },
    keywords: {
      title: 'Most used words',
      intro: 'Common words and very short words are left out. A word repeated many times can make a text feel stuffed.',
      empty: 'Write a few more words to see which ones you use most.',
      times: '{n} times',
    },
    example: 'This is an example text. Replace it with yours.',
    clear: 'Clear',
    copyStats: 'Copy the counts',
    summary: '{words} words, {characters} characters ({noSpaces} without spaces), {sentences} sentences, about {time} to read.',
    notice:
      'Characters are counted as written letters, so an Arabic letter or an emoji counts once. Reading time uses the speed you choose and is only an estimate. Other tools may count words or characters a little differently.',
    steps: [
      'Paste or type your text in the box.',
      'Read the counts and the reading time, and pick a reading speed if you want.',
      'Check the length limits and the most used words, and edit until the text fits.',
    ],
    faq: [
      {
        q: 'Does it count Arabic correctly?',
        a: 'Yes. A word is a run of letters and digits, and Arabic marks such as the vowel signs stay with their letters. Sentences end at a full stop, an exclamation mark, a question mark (including the Arabic one) or a new line.',
      },
      {
        q: 'How is reading time worked out?',
        a: 'By dividing the number of words by a reading speed, 200 words a minute by default. People read at different speeds, so treat it as an estimate and change the speed if you know yours.',
      },
      {
        q: 'Why is the character count different in another tool?',
        a: 'Tools disagree about line breaks, spaces and symbols made of several parts, such as some emoji. Here every written character counts once. If a platform has a hard limit, check the text with that platform.',
      },
      {
        q: 'What are the length limits for?',
        a: 'They show how much room a text has in places where length matters: a page title, a search description, an SMS, a post. They are commonly quoted figures and the platforms can change them.',
      },
      {
        q: 'Is my text stored or sent?',
        a: 'No. It is counted in your browser and never sent anywhere.',
      },
    ],
    cta: {
      title: 'Words that bring people in',
      text: 'We plan and write content and social media in Arabic and English, tied to what your customers search for and what you want them to do.',
      button: 'See content and social media',
    },
  },

  seofiles: {
    h1: 'Robots.txt and sitemap generator',
    subtitle: 'Build the two files that guide search engines, check your rules, and test whether a crawler may open a path.',
    tabLabel: 'File',
    tabs: { robots: 'robots.txt', sitemap: 'sitemap.xml' },
    presetLabel: 'Start from',
    presets: { allow: 'Allow everything', block: 'Block everything', store: 'Online store', wordpress: 'WordPress', ai: 'Block AI crawlers' },
    fields: {
      agents: 'Crawlers',
      disallow: 'Do not allow',
      allow: 'Allow',
      crawlDelay: 'Crawl delay in seconds',
      sitemaps: 'Sitemap addresses',
    },
    hints: {
      agents: 'One crawler name per line. Use * for all of them.',
      disallow: 'One path per line, such as /admin/ or /*.pdf$.',
      allow: 'Paths that stay open inside a blocked one.',
      crawlDelay: 'Optional. Google ignores it; some other crawlers follow it.',
      sitemaps: 'One full address per line, such as https://example.com/sitemap.xml.',
    },
    checks: {
      title: 'Checks',
      allGood: 'No problems found.',
      noAgent: 'Add at least one crawler name, or * for all of them.',
      badPath: '"{value}" must start with / or *.',
      blocksAll: 'This blocks the whole site for every crawler. Use it only when that is what you want.',
      badSitemap: '"{value}" must be a full address that starts with http:// or https://.',
      crawlDelay: 'Google ignores the crawl delay.',
    },
    test: {
      title: 'Test a path',
      crawler: 'Crawler',
      crawlerPlaceholder: 'Googlebot',
      path: 'Path to test',
      pathPlaceholder: '/admin/login',
      allowed: 'Allowed',
      blocked: 'Blocked',
      byRule: 'by the rule {rule}',
      noRule: 'No rule matches this path, so it is allowed.',
      noGroup: 'No group applies to this crawler, so it is allowed.',
    },
    sitemap: {
      urls: 'Page addresses',
      urlsHint: 'One per line. After an address you can add a last modified date, like 2026-09-01.',
      loadExample: 'Fill with an example',
      count: '{n} addresses',
      invalid: '{n} lines could not be used: {lines}',
      duplicates: '{n} repeated addresses were left out.',
      mixedHosts: 'The addresses are on more than one site ({hosts}). A sitemap should list one site.',
      tooMany: 'A sitemap can hold at most 50,000 addresses. Split it into several.',
      empty: 'Add some addresses to build the sitemap.',
    },
    output: 'The file',
    download: { robots: 'Download robots.txt', sitemap: 'Download sitemap.xml' },
    copyFile: 'Copy',
    where: {
      robots: 'Put robots.txt at the root of your site, for example https://example.com/robots.txt.',
      sitemap: 'Put sitemap.xml on your site, then list its address in robots.txt or in Google Search Console.',
    },
    notice:
      'robots.txt asks crawlers to stay away from paths. It does not hide a page or protect it, and a crawler can ignore it, so never use it to keep something private. Add a last modified date only when it is true; a wrong date makes search engines trust the sitemap less.',
    steps: [
      'Choose a starting point, then change the crawlers, the blocked paths and the allowed paths.',
      'Read the checks, and test a path to see which rule decides it.',
      'Download the file, put it on your site, and build the sitemap on the other tab.',
    ],
    faq: [
      {
        q: 'What does robots.txt do?',
        a: 'It tells crawlers which parts of a site they should not request. Search engines such as Google follow it. It is a request, not a lock, so it cannot keep a page private.',
      },
      {
        q: 'Which rule wins when two rules match?',
        a: 'The longest matching rule wins, because it is the most specific. If an Allow and a Disallow match with the same length, the Allow wins. The test box shows which rule decided.',
      },
      {
        q: 'Should I block AI crawlers?',
        a: 'That is your choice. The preset lists crawler names that their companies publish for this, and well-behaved ones follow it. It will not stop a crawler that ignores robots.txt.',
      },
      {
        q: 'Do I need a sitemap?',
        a: 'Small sites that are well linked are usually found without one. A sitemap helps search engines find pages on larger sites, new sites and sites with pages that are hard to reach by links.',
      },
      {
        q: 'Is anything stored or sent?',
        a: 'No. The files are built in your browser and nothing you type is sent anywhere.',
      },
    ],
    cta: {
      title: 'Crawl rules are one part of technical SEO',
      text: 'We handle crawling, indexing, canonical and hreflang tags, sitemaps and rendering across whole sites, in Arabic and English.',
      button: 'See SEO services',
    },
  },

  invoice: {
    h1: 'Invoice generator',
    subtitle: 'Fill in the details and watch the invoice build up. VAT is worked out per line. Print it or save it as a PDF from your browser.',
    sections: { seller: 'From', buyer: 'To', details: 'Invoice details', items: 'Items' },
    fields: {
      sellerName: 'Your business name',
      sellerAddress: 'Address',
      sellerTaxId: 'Tax number',
      sellerEmail: 'Email',
      buyerName: 'Client name',
      buyerAddress: 'Address',
      buyerTaxId: 'Tax number',
      number: 'Invoice number',
      issueDate: 'Issue date',
      terms: 'Payment terms',
      currency: 'Currency',
      notes: 'Notes',
    },
    hints: { issueDate: 'Year, month, day: 2026-01-15.', currency: 'A short label, such as SAR or USD.' },
    terms: { 0: 'Due on receipt', 7: 'Within 7 days', 14: 'Within 14 days', 30: 'Within 30 days', 60: 'Within 60 days' },
    item: {
      description: 'Description',
      quantity: 'Qty',
      price: 'Unit price',
      rate: 'VAT',
      line: 'Line {n}',
      add: 'Add a line',
      remove: 'Remove line {n}',
    },
    errors: {
      date: 'Use the form 2026-01-15.',
      quantity: 'A number above zero.',
      price: 'A price such as 250 or 99.50.',
    },
    status: { label: 'Status', draft: 'Draft', paid: 'Paid' },
    paper: {
      invoice: 'Invoice',
      from: 'From',
      to: 'To',
      taxNumber: 'Tax number',
      issued: 'Issued',
      due: 'Due',
      description: 'Description',
      quantity: 'Qty',
      unitPrice: 'Unit price',
      vat: 'VAT',
      amount: 'Amount',
      subtotal: 'Subtotal',
      vatTotal: 'VAT',
      vatAt: 'VAT {rate}%',
      total: 'Total',
      notes: 'Notes',
      empty: 'Add a line with a description, a quantity and a price to see the invoice.',
      stamp: 'PAID',
    },
    print: 'Print or save as PDF',
    copyText: 'Copy as text',
    nextNumber: 'Next number',
    loadExample: 'Fill with an example',
    clear: 'Clear',
    notice:
      'This makes a simple invoice. Some countries require invoices to be issued through an approved e-invoicing system, for example Saudi Arabia\'s Fatoora, and this tool does not produce those. Prices are entered before VAT and the VAT is added per line, rounded to the nearest cent. Check the rules with your tax authority or accountant.',
    steps: [
      'Fill in who the invoice is from and to, the number and the date.',
      'Add a line for each item, with its quantity, price and VAT rate.',
      'Press "Print or save as PDF" and choose "Save as PDF" in the print window.',
    ],
    faq: [
      {
        q: 'How do I save the invoice as a PDF?',
        a: 'Press "Print or save as PDF". In the window that opens, choose "Save as PDF" as the destination. Only the invoice is printed, not the rest of the page.',
      },
      {
        q: 'How is VAT worked out?',
        a: 'Prices are entered before VAT. For each line the quantity is multiplied by the price, VAT is added at that line\'s rate and rounded to the nearest cent, and the totals are the sums of the lines, so everything on the invoice adds up.',
      },
      {
        q: 'Can I use different VAT rates on one invoice?',
        a: 'Yes. Choose a rate for each line. The invoice shows the VAT for each rate and the total.',
      },
      {
        q: 'Is this a valid tax invoice?',
        a: 'It has the usual parts of an invoice, but each country has its own rules, and some require an approved e-invoicing system. Check what applies to you before you rely on it.',
      },
      {
        q: 'Is my invoice stored or sent?',
        a: 'No. It is made in your browser and nothing you type is sent anywhere. It is lost when you close the page, so save the PDF.',
      },
    ],
    cta: {
      title: 'Invoicing that runs itself',
      text: 'We build billing, invoicing and online payment flows that handle VAT per country, in Arabic and English, and connect to your accounts.',
      button: 'See digital solutions',
    },
  },
};

const ar = {
  hub: {
    wordcount: {
      title: 'عدّاد الكلمات والحروف',
      text: 'عدّ الكلمات والحروف والجمل ووقت القراءة بالعربية أو الإنجليزية، وشاهد أكثر الكلمات تكراراً، وراجع حدود الطول الشائعة.',
    },
    seofiles: {
      title: 'مولّد robots.txt وخريطة الموقع',
      text: 'ابنِ ملفي robots.txt وsitemap.xml، وراجع القواعد، واختبر هل يستطيع زاحف فتح مسار.',
    },
    invoice: {
      title: 'مولّد الفواتير',
      text: 'اصنع فاتورة أنيقة بضريبة لكل بند، ثم اطبعها أو احفظها PDF من متصفحك.',
    },
  },

  wordcount: {
    h1: 'عدّاد الكلمات والحروف',
    subtitle: 'الصق نصاً أو اكتبه وتتحدث الأرقام وأنت تكتب. يعمل بالعربية والإنجليزية، ولا يغادر شيء متصفحك.',
    textLabel: 'نصك',
    placeholder: 'اكتب نصك هنا أو الصقه…',
    stats: {
      words: 'الكلمات',
      characters: 'الحروف',
      charactersNoSpaces: 'بدون مسافات',
      sentences: 'الجمل',
      paragraphs: 'الفقرات',
      reading: 'وقت القراءة',
      speaking: 'وقت الإلقاء',
    },
    time: '{m} د {s} ث',
    speedLabel: 'سرعة القراءة',
    speeds: { slow: 'بطيئة', average: 'متوسطة', fast: 'سريعة' },
    speedNote: 'نحو {n} كلمة في الدقيقة. وقت القراءة تقدير.',
    limits: {
      title: 'الحدود',
      intro: 'حدود طول شائعة، وهي أرقام يكثر ذكرها. راجع القواعد الحالية للمكان الذي تنشر فيه.',
      names: { title: 'عنوان الصفحة', description: 'وصف meta', sms: 'رسالة SMS واحدة', x: 'منشور X', caption: 'تعليق إنستغرام' },
      left: 'متبقٍ {n}',
      over: 'زائد {n}',
    },
    keywords: {
      title: 'أكثر الكلمات استخداماً',
      intro: 'تُستبعد الكلمات الشائعة والكلمات القصيرة جداً. وتكرار كلمة مرات كثيرة قد يجعل النص يبدو محشواً.',
      empty: 'اكتب بضع كلمات أخرى لترى أيها تستخدم أكثر.',
      times: '{n} مرات',
    },
    example: 'هذا نص مثال. استبدله بنصك.',
    clear: 'امسح',
    copyStats: 'انسخ الأرقام',
    summary: '{words} كلمة، {characters} حرفاً ({noSpaces} بدون مسافات)، {sentences} جملة، ونحو {time} للقراءة.',
    notice:
      'تُحسب الحروف كما هي مكتوبة، فالحرف العربي أو الإيموجي يُحسب مرة واحدة. ويستخدم وقت القراءة السرعة التي تختارها وهو تقدير فقط. وقد تعدّ أدوات أخرى الكلمات أو الحروف بفارق بسيط.',
    steps: [
      'الصق نصك أو اكتبه في الخانة.',
      'اقرأ الأرقام ووقت القراءة، واختر سرعة قراءة إن أردت.',
      'راجع حدود الطول وأكثر الكلمات استخداماً، وعدّل حتى يناسب النص.',
    ],
    faq: [
      {
        q: 'هل يعدّ العربية بشكل صحيح؟',
        a: 'نعم. الكلمة سلسلة من الحروف والأرقام، وتبقى علامات التشكيل مع حروفها. وتنتهي الجملة عند نقطة أو علامة تعجب أو علامة استفهام (ومنها العربية) أو سطر جديد.',
      },
      {
        q: 'كيف يُحسب وقت القراءة؟',
        a: 'بقسمة عدد الكلمات على سرعة قراءة، وهي 200 كلمة في الدقيقة افتراضياً. يختلف الناس في سرعة القراءة، فاعتبره تقديراً وغيّر السرعة إن عرفت سرعتك.',
      },
      {
        q: 'لماذا يختلف عدد الحروف في أداة أخرى؟',
        a: 'تختلف الأدوات في معاملة فواصل الأسطر والمسافات والرموز المكوّنة من عدة أجزاء مثل بعض الإيموجي. وهنا يُحسب كل حرف مكتوب مرة واحدة. وإن كان للمنصة حد صارم فتحقق من النص عندها.',
      },
      {
        q: 'لماذا توجد حدود الطول؟',
        a: 'لتُظهر كم من المساحة يملك النص في أماكن يهم فيها الطول: عنوان الصفحة ووصف البحث ورسالة SMS والمنشور. وهي أرقام يكثر ذكرها وقد تغيّرها المنصات.',
      },
      {
        q: 'هل يُخزَّن نصي أو يُرسَل؟',
        a: 'لا. يُعدّ في متصفحك ولا يُرسل إلى أي مكان.',
      },
    ],
    cta: {
      title: 'كلمات تجلب الناس',
      text: 'نخطط ونكتب المحتوى ومنصات التواصل بالعربية والإنجليزية، مرتبطاً بما يبحث عنه عملاؤك وبما تريدهم أن يفعلوه.',
      button: 'تعرّف على المحتوى والتواصل الاجتماعي',
    },
  },

  seofiles: {
    h1: 'مولّد robots.txt وخريطة الموقع',
    subtitle: 'ابنِ الملفين اللذين يوجّهان محركات البحث، وراجع قواعدك، واختبر هل يستطيع زاحف فتح مسار.',
    tabLabel: 'الملف',
    tabs: { robots: 'robots.txt', sitemap: 'sitemap.xml' },
    presetLabel: 'ابدأ من',
    presets: { allow: 'السماح بكل شيء', block: 'حظر كل شيء', store: 'متجر إلكتروني', wordpress: 'ووردبريس', ai: 'حظر زواحف الذكاء الاصطناعي' },
    fields: {
      agents: 'الزواحف',
      disallow: 'عدم السماح',
      allow: 'السماح',
      crawlDelay: 'تأخير الزحف بالثواني',
      sitemaps: 'عناوين خرائط الموقع',
    },
    hints: {
      agents: 'اسم زاحف في كل سطر. استخدم * لكلها.',
      disallow: 'مسار في كل سطر، مثل /admin/ أو /*.pdf$.',
      allow: 'مسارات تبقى مفتوحة داخل مسار محظور.',
      crawlDelay: 'اختياري. تتجاهله جوجل، وتتبعه بعض الزواحف الأخرى.',
      sitemaps: 'عنوان كامل في كل سطر، مثل https://example.com/sitemap.xml.',
    },
    checks: {
      title: 'الفحوص',
      allGood: 'لم تُوجد مشكلات.',
      noAgent: 'أضف اسم زاحف واحداً على الأقل، أو * لكلها.',
      badPath: '"{value}" يجب أن يبدأ بـ / أو *.',
      blocksAll: 'هذا يحظر الموقع كله على كل الزواحف. استخدمه فقط إن كان هذا ما تريده.',
      badSitemap: '"{value}" يجب أن يكون عنواناً كاملاً يبدأ بـ http:// أو https://.',
      crawlDelay: 'تتجاهل جوجل تأخير الزحف.',
    },
    test: {
      title: 'اختبر مساراً',
      crawler: 'الزاحف',
      crawlerPlaceholder: 'Googlebot',
      path: 'المسار المراد اختباره',
      pathPlaceholder: '/admin/login',
      allowed: 'مسموح',
      blocked: 'محظور',
      byRule: 'بحسب القاعدة {rule}',
      noRule: 'لا تنطبق قاعدة على هذا المسار، فهو مسموح.',
      noGroup: 'لا تنطبق مجموعة على هذا الزاحف، فهو مسموح.',
    },
    sitemap: {
      urls: 'عناوين الصفحات',
      urlsHint: 'عنوان في كل سطر. وبعد العنوان يمكنك إضافة تاريخ آخر تعديل مثل 2026-09-01.',
      loadExample: 'املأ بمثال',
      count: '{n} عنواناً',
      invalid: 'تعذّر استخدام {n} سطراً: {lines}',
      duplicates: 'تُركت {n} عناوين مكررة.',
      mixedHosts: 'العناوين على أكثر من موقع ({hosts}). يجب أن تسرد خريطة الموقع موقعاً واحداً.',
      tooMany: 'تتسع خريطة الموقع لـ 50,000 عنوان على الأكثر. قسّمها إلى عدة خرائط.',
      empty: 'أضف بعض العناوين لتبني خريطة الموقع.',
    },
    output: 'الملف',
    download: { robots: 'نزّل robots.txt', sitemap: 'نزّل sitemap.xml' },
    copyFile: 'انسخ',
    where: {
      robots: 'ضع robots.txt في جذر موقعك، مثل https://example.com/robots.txt.',
      sitemap: 'ضع sitemap.xml على موقعك، ثم اذكر عنوانه في robots.txt أو في Google Search Console.',
    },
    notice:
      'يطلب robots.txt من الزواحف الابتعاد عن مسارات. وهو لا يخفي صفحة ولا يحميها، ويستطيع الزاحف تجاهله، فلا تستخدمه لإبقاء شيء خاصاً. وأضف تاريخ آخر تعديل فقط حين يكون صحيحاً؛ فالتاريخ الخاطئ يقلل ثقة محركات البحث بخريطة الموقع.',
    steps: [
      'اختر نقطة بداية، ثم عدّل الزواحف والمسارات المحظورة والمسارات المسموحة.',
      'اقرأ الفحوص، واختبر مساراً لترى أي قاعدة تحسمه.',
      'نزّل الملف وضعه على موقعك، وابنِ خريطة الموقع في التبويب الآخر.',
    ],
    faq: [
      {
        q: 'ماذا يفعل robots.txt؟',
        a: 'يخبر الزواحف أي أجزاء من الموقع لا ينبغي أن تطلبها. وتتبعه محركات بحث مثل جوجل. وهو طلب لا قفل، فلا يستطيع إبقاء صفحة خاصة.',
      },
      {
        q: 'أي قاعدة تفوز عند تطابق قاعدتين؟',
        a: 'تفوز القاعدة المطابقة الأطول، لأنها الأكثر تحديداً. وإن تطابقت قاعدة سماح وقاعدة منع بالطول نفسه فيفوز السماح. ويُظهر مربع الاختبار القاعدة التي حسمت.',
      },
      {
        q: 'هل أحظر زواحف الذكاء الاصطناعي؟',
        a: 'هذا قرارك. تسرد القاعدة الجاهزة أسماء زواحف تنشرها شركاتها لهذا الغرض، وتتبعها الملتزمة منها. ولن توقف زاحفاً يتجاهل robots.txt.',
      },
      {
        q: 'هل أحتاج خريطة موقع؟',
        a: 'المواقع الصغيرة المترابطة جيداً تُكتشف عادةً من غيرها. وتساعد خريطة الموقع محركات البحث على إيجاد الصفحات في المواقع الكبيرة والجديدة والتي فيها صفحات يصعب الوصول إليها بالروابط.',
      },
      {
        q: 'هل يُخزَّن أو يُرسَل شيء؟',
        a: 'لا. تُبنى الملفات في متصفحك ولا يُرسل ما تكتبه إلى أي مكان.',
      },
    ],
    cta: {
      title: 'قواعد الزحف جزء من السيو التقني',
      text: 'نتولى الزحف والأرشفة ووسوم canonical وhreflang وخرائط الموقع والعرض على مواقع كاملة، بالعربية والإنجليزية.',
      button: 'تعرّف على خدمات السيو',
    },
  },

  invoice: {
    h1: 'مولّد الفواتير',
    subtitle: 'املأ البيانات وشاهد الفاتورة تتكوّن. تُحسب الضريبة لكل بند. اطبعها أو احفظها PDF من متصفحك.',
    sections: { seller: 'من', buyer: 'إلى', details: 'بيانات الفاتورة', items: 'البنود' },
    fields: {
      sellerName: 'اسم نشاطك',
      sellerAddress: 'العنوان',
      sellerTaxId: 'الرقم الضريبي',
      sellerEmail: 'البريد الإلكتروني',
      buyerName: 'اسم العميل',
      buyerAddress: 'العنوان',
      buyerTaxId: 'الرقم الضريبي',
      number: 'رقم الفاتورة',
      issueDate: 'تاريخ الإصدار',
      terms: 'شروط الدفع',
      currency: 'العملة',
      notes: 'ملاحظات',
    },
    hints: { issueDate: 'سنة-شهر-يوم: 2026-01-15.', currency: 'رمز قصير مثل SAR أو USD.' },
    terms: { 0: 'مستحقة عند الاستلام', 7: 'خلال 7 أيام', 14: 'خلال 14 يوماً', 30: 'خلال 30 يوماً', 60: 'خلال 60 يوماً' },
    item: {
      description: 'الوصف',
      quantity: 'الكمية',
      price: 'سعر الوحدة',
      rate: 'الضريبة',
      line: 'البند {n}',
      add: 'أضف بنداً',
      remove: 'احذف البند {n}',
    },
    errors: {
      date: 'استخدم الصيغة 2026-01-15.',
      quantity: 'رقم أكبر من صفر.',
      price: 'سعر مثل 250 أو 99.50.',
    },
    status: { label: 'الحالة', draft: 'مسودة', paid: 'مدفوعة' },
    paper: {
      invoice: 'فاتورة',
      from: 'من',
      to: 'إلى',
      taxNumber: 'الرقم الضريبي',
      issued: 'تاريخ الإصدار',
      due: 'تاريخ الاستحقاق',
      description: 'الوصف',
      quantity: 'الكمية',
      unitPrice: 'سعر الوحدة',
      vat: 'الضريبة',
      amount: 'المبلغ',
      subtotal: 'الإجمالي قبل الضريبة',
      vatTotal: 'الضريبة',
      vatAt: 'ضريبة {rate}%',
      total: 'الإجمالي',
      notes: 'ملاحظات',
      empty: 'أضف بنداً فيه وصف وكمية وسعر لترى الفاتورة.',
      stamp: 'مدفوعة',
    },
    print: 'اطبع أو احفظ PDF',
    copyText: 'انسخ كنص',
    nextNumber: 'الرقم التالي',
    loadExample: 'املأ بمثال',
    clear: 'امسح',
    notice:
      'تصنع هذه الأداة فاتورة بسيطة. تشترط بعض الدول أن تصدر الفواتير عبر نظام فوترة إلكترونية معتمد، مثل «فاتورة» في السعودية، ولا تنتج هذه الأداة تلك الفواتير. تُدخل الأسعار قبل الضريبة وتُضاف الضريبة لكل بند وتُقرَّب إلى أقرب هللة. راجع القواعد مع الهيئة الضريبية أو المحاسب.',
    steps: [
      'املأ من وإلى من الفاتورة، ورقمها وتاريخها.',
      'أضف بنداً لكل صنف، بكميته وسعره ونسبة ضريبته.',
      'اضغط «اطبع أو احفظ PDF» واختر «حفظ بصيغة PDF» في نافذة الطباعة.',
    ],
    faq: [
      {
        q: 'كيف أحفظ الفاتورة PDF؟',
        a: 'اضغط «اطبع أو احفظ PDF». وفي النافذة التي تفتح اختر «حفظ بصيغة PDF» وجهةً. تُطبع الفاتورة وحدها لا بقية الصفحة.',
      },
      {
        q: 'كيف تُحسب الضريبة؟',
        a: 'تُدخل الأسعار قبل الضريبة. في كل بند تُضرب الكمية في السعر، وتُضاف الضريبة بنسبة ذلك البند وتُقرَّب إلى أقرب هللة، والإجماليات هي مجموع البنود، فيتطابق كل ما في الفاتورة.',
      },
      {
        q: 'هل أستطيع استخدام نسب ضريبة مختلفة في فاتورة واحدة؟',
        a: 'نعم. اختر نسبة لكل بند. وتُظهر الفاتورة الضريبة لكل نسبة والإجمالي.',
      },
      {
        q: 'هل هذه فاتورة ضريبية صالحة؟',
        a: 'فيها الأجزاء المعتادة للفاتورة، لكن لكل دولة قواعدها، وبعضها يشترط نظام فوترة إلكترونية معتمداً. تحقق مما ينطبق عليك قبل أن تعتمد عليها.',
      },
      {
        q: 'هل تُخزَّن فاتورتي أو تُرسَل؟',
        a: 'لا. تُصنع في متصفحك ولا يُرسل ما تكتبه إلى أي مكان. وتضيع عند إغلاق الصفحة، فاحفظ الـ PDF.',
      },
    ],
    cta: {
      title: 'فوترة تعمل وحدها',
      text: 'نبني مسارات الفوترة والفواتير والدفع الإلكتروني التي تتعامل مع الضريبة لكل دولة، بالعربية والإنجليزية، وتتصل بحساباتك.',
      button: 'تعرّف على الحلول الرقمية',
    },
  },
};

export const batch5Content = { en, ar };
