// Copy for the second batch of free tools: Hijri converter, structured-data generator and
// project brief writer. English and Arabic must keep the same shape (a test checks it).

const en = {
  hub: {
    hijri: {
      title: 'Hijri Date Converter',
      text: 'Convert between Hijri and Gregorian dates, see the weekday, the month calendar and the moon.',
    },
    schema: {
      title: 'Structured Data Generator',
      text: 'Fill in a form and get JSON-LD for your company, shop, article or FAQ, checked as you type.',
    },
    brief: {
      title: 'Project Brief Writer',
      text: 'Answer a few questions and get a clear brief you can send to any agency or freelancer.',
    },
  },

  hijri: {
    h1: 'Hijri date converter',
    subtitle: 'Convert between Hijri and Gregorian dates, and see the weekday, the whole Hijri month and the moon for that day.',
    modeLabel: 'Direction',
    modes: { g: 'Gregorian to Hijri', h: 'Hijri to Gregorian' },
    day: 'Day',
    month: 'Month',
    year: 'Year',
    today: 'Use today',
    hijriLabel: 'Hijri',
    gregorianLabel: 'Gregorian',
    weekdayLabel: 'Day of the week',
    suffixHijri: 'AH',
    suffixGregorian: 'CE',
    copyResult: 'Copy the date',
    equals: 'which is',
    errors: {
      invalid: 'That date does not exist. Check the day and the month.',
      range: 'Dates are supported from 1901 to 2076 (about 1318 to 1499 AH).',
      unsupported: 'This browser does not include the Umm al-Qura calendar, so it cannot convert dates.',
      day30: 'This Hijri month has 29 days.',
    },
    moon: {
      title: 'The moon that day',
      illuminated: 'lit',
      approximate: 'Calculated from the average lunar cycle. The real moon can be up to half a day away from this.',
      phases: {
        new: 'New moon',
        waxingCrescent: 'Waxing crescent',
        firstQuarter: 'First quarter',
        waxingGibbous: 'Waxing gibbous',
        full: 'Full moon',
        waningGibbous: 'Waning gibbous',
        lastQuarter: 'Last quarter',
        waningCrescent: 'Waning crescent',
      },
    },
    calendar: {
      title: 'The month at a glance',
      days: 'days',
      weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      pick: 'Open this day',
    },
    approximate:
      'Dates use the Umm al-Qura calendar, which is calculated in advance. A month can start a day earlier or later where the crescent is sighted locally, so check with your local authority for religious dates.',
    steps: [
      'Choose the direction: Gregorian to Hijri, or Hijri to Gregorian.',
      'Type the day, the month and the year, or press "Use today".',
      'Read the converted date, the weekday and the moon, or tap a day in the month calendar to jump to it.',
    ],
    faq: [
      {
        q: 'Which Hijri calendar does it use?',
        a: 'The Umm al-Qura calendar, which your browser includes. It is the calendar used officially in Saudi Arabia and it is calculated in advance, not sighted.',
      },
      {
        q: 'Why can a date differ by a day from my country?',
        a: 'Some countries start the month when the crescent is sighted, which can be a day before or after the calculated date. For religious occasions such as Ramadan and the two Eids, follow the announcement of your local authority.',
      },
      {
        q: 'Which years can I convert?',
        a: 'Gregorian years 1901 to 2076, which are about 1318 to 1499 in the Hijri calendar. These are the years the Umm al-Qura calendar in browsers covers.',
      },
      {
        q: 'How is the moon worked out?',
        a: 'From the average length of the lunar month, counted from a known new moon. It is a close estimate for the picture and the phase name, but real new and full moons can differ by up to half a day.',
      },
      {
        q: 'Is anything stored or sent?',
        a: 'No. The conversion is done by your browser and nothing you type is sent anywhere.',
      },
    ],
    cta: {
      title: 'Building for an Arabic audience?',
      text: 'We build Arabic-first websites and apps with right-to-left layouts, Hijri dates and bilingual content done properly from the start.',
      button: 'See digital solutions',
    },
  },

  schema: {
    h1: 'Structured data generator',
    subtitle: 'Fill in a form and get JSON-LD for your company, shop, article or FAQ, checked as you type.',
    typeLabel: 'What is the markup for?',
    types: {
      Organization: 'Company',
      LocalBusiness: 'Local business',
      FAQPage: 'FAQ',
      Article: 'Article',
    },
    fields: {
      name: 'Name',
      url: 'Web address',
      logo: 'Logo address',
      email: 'Email',
      telephone: 'Phone',
      sameAs: 'Other profiles',
      image: 'Image address',
      street: 'Street',
      city: 'City',
      region: 'Region',
      postalCode: 'Postal code',
      country: 'Country code',
      hours: 'Opening hours',
      priceRange: 'Price range',
      headline: 'Headline',
      author: 'Author',
      datePublished: 'Date published',
      dateModified: 'Date modified',
      publisher: 'Publisher',
    },
    hints: {
      sameAs: 'One address per line: social profiles, a Wikipedia page.',
      country: 'Two letters, such as SA, AE or EG.',
      hours: 'For example Mo-Fr 09:00-17:00.',
      priceRange: 'For example $$.',
      datePublished: 'Year, month, day: 2026-01-15.',
      dateModified: 'Year, month, day: 2026-01-15.',
      headline: 'Common guidance: up to 110 characters.',
    },
    faqQuestion: 'Question',
    faqAnswer: 'Answer',
    faqItem: 'Question {n}',
    addQuestion: 'Add a question',
    removeQuestion: 'Remove question {n}',
    loadExample: 'Fill with an example',
    clear: 'Clear',
    output: 'Code to paste',
    copyCode: 'Copy the code',
    readiness: 'Required fields',
    checklist: 'Checks',
    status: {
      ok: 'Good',
      missing: 'Missing',
      invalid: 'Needs a fix',
      long: 'Long',
    },
    levels: { required: 'required', recommended: 'recommended', optional: 'optional' },
    problems: {
      invalid: 'This value does not look right.',
      long: 'Longer than the common limit, so it may be cut off.',
      faqPair: 'Fill in both the question and the answer.',
      faqMissing: 'Add at least one question with its answer.',
    },
    tryGoogle: "Test it with Google's Rich Results Test",
    placeUse: 'Paste it into the <head> or the <body> of the page it describes.',
    notice:
      'A good result here means the markup is complete. It does not mean Google will show a rich result, and the text must match what is visible on the page.',
    steps: [
      'Choose what the markup is for: a company, a local business, an FAQ or an article.',
      'Fill in the fields. The checks on the side show what is missing or needs a fix.',
      'Copy the code, paste it into the page it describes, and test it with Google\'s Rich Results Test.',
    ],
    faq: [
      {
        q: 'What is JSON-LD?',
        a: 'It is a block of data placed in a page that tells search engines in a fixed format what the page is about, such as the name, address and opening hours of a business. People do not see it.',
      },
      {
        q: 'Will it give me rich results in Google?',
        a: 'Not by itself. Valid markup makes a page eligible for some kinds of rich results, but Google decides whether to show them. Nothing here changes your ranking directly.',
      },
      {
        q: 'Where do I put the code?',
        a: 'Inside the page it describes, in the head or the body. On most website builders there is a place for custom code or a field for header scripts.',
      },
      {
        q: 'Why must the text match the page?',
        a: 'Google asks that structured data describes what visitors can actually see. Markup for questions or details that are not on the page can be ignored or treated as a violation of its guidelines.',
      },
      {
        q: 'Is anything stored or sent?',
        a: 'No. The code is built in your browser and nothing you type is sent anywhere. The test link only opens Google\'s tool in a new tab.',
      },
    ],
    cta: {
      title: 'Structured data is one part of technical SEO',
      text: 'We implement it across whole sites with the right types for each page, together with canonical and hreflang tags, sitemaps and crawlable rendering.',
      button: 'See SEO services',
    },
  },

  brief: {
    h1: 'Project brief writer',
    subtitle: 'Answer a few questions and get a clear brief you can send to any agency or freelancer.',
    fields: {
      name: 'Project or company name',
      type: 'What do you need?',
      goal: 'What should it achieve?',
      audience: 'Who is it for?',
      budget: 'Budget range',
      timeline: 'When do you need it?',
      features: 'What must it include?',
      references: 'Sites or apps you like',
      notes: 'Anything else',
    },
    placeholders: {
      name: 'Dana Perfumes',
      goal: 'Double our online sales within six months.',
      audience: 'Women 25 to 45 in Saudi Arabia and the UAE.',
      references: 'example.com, another-example.com',
      notes: 'Constraints, existing systems, people who must approve.',
    },
    hints: {
      goal: 'One clear outcome is better than a list of wishes.',
      references: 'Separate with commas or new lines.',
    },
    types: {
      website: 'Company website',
      store: 'Online store',
      app: 'Mobile app',
      ads: 'Advertising campaign',
      brand: 'Brand identity',
      seo: 'SEO',
      other: 'Something else',
    },
    budgets: {
      b1: 'Under 3,000 USD',
      b2: '3,000 to 10,000 USD',
      b3: '10,000 to 30,000 USD',
      b4: 'Over 30,000 USD',
      undecided: 'Not decided yet',
    },
    timelines: {
      t1: 'Within a month',
      t2: '1 to 3 months',
      t3: 'More than 3 months',
      flexible: 'Flexible',
    },
    features: {
      bilingual: 'Arabic and English',
      payments: 'Online payments',
      booking: 'Bookings',
      dashboard: 'Admin dashboard',
      integrations: 'Integrations with other systems',
      analytics: 'Analytics and tracking',
      content: 'Content writing',
      seo: 'Search optimisation',
    },
    document: {
      documentTitle: 'Project brief',
      openQuestions: 'Still to decide',
      sections: {
        type: 'What is needed',
        goal: 'Goal',
        audience: 'Audience',
        budget: 'Budget',
        timeline: 'Timeline',
        features: 'Must include',
        references: 'References',
        notes: 'Notes',
      },
      placeholderTitle: 'Your project',
      empty: 'Waiting for your answer',
    },
    progress: 'Brief completeness',
    progressDone: 'Ready to send',
    copy: 'Copy the brief',
    download: 'Download as text file',
    sendToUs: 'Copy it and open the contact form',
    sendHint: 'Paste it in the project description of the form.',
    fileName: 'project-brief.txt',
    steps: [
      'Fill in the questions on the left. The brief on the right is written as you type.',
      'Fill the six marked sections. Whatever is left is listed at the end as questions still to decide.',
      'Copy the brief or download it as a text file and send it to the people you want a quote from.',
    ],
    faq: [
      {
        q: 'Why write a brief at all?',
        a: 'A clear brief means the quotes you get describe the same work, so they can be compared. It also saves a first call that would only be spent asking these questions.',
      },
      {
        q: 'Do I have to know the budget?',
        a: 'No. Choose "Not decided yet" and the brief will say so. Giving a range usually gets more realistic proposals than leaving it out.',
      },
      {
        q: 'Can I use the brief with other agencies?',
        a: 'Yes. It is plain text and it is yours. Send it to as many people as you like.',
      },
      {
        q: 'What do I do with the "still to decide" list?',
        a: 'Those are the core questions you left empty. A good agency will ask them anyway, so answering them early speeds up the quote.',
      },
      {
        q: 'Is anything stored or sent?',
        a: 'No. The brief is written in your browser and nothing you type is sent anywhere. It leaves your device only when you copy it, download it or paste it somewhere yourself.',
      },
    ],
    cta: {
      title: 'Want us to look at your brief?',
      text: 'Send it with the contact form. We reply with questions, an approach and a realistic scope, not a template quote.',
      button: 'See digital solutions',
    },
  },
};

const ar = {
  hub: {
    hijri: {
      title: 'محوّل التاريخ الهجري والميلادي',
      text: 'حوّل بين التاريخ الهجري والميلادي، وشاهد اليوم وتقويم الشهر والقمر.',
    },
    schema: {
      title: 'مولّد البيانات المنظمة',
      text: 'املأ النموذج واحصل على JSON-LD لشركتك أو متجرك أو مقالك أو أسئلتك، مع فحص أثناء الكتابة.',
    },
    brief: {
      title: 'كاتب موجز المشروع',
      text: 'أجب عن بضعة أسئلة واحصل على موجز واضح ترسله لأي شركة أو مستقل.',
    },
  },

  hijri: {
    h1: 'محوّل التاريخ الهجري والميلادي',
    subtitle: 'حوّل بين التاريخ الهجري والميلادي، وشاهد اليوم من الأسبوع والشهر الهجري كاملاً وحالة القمر في ذلك اليوم.',
    modeLabel: 'الاتجاه',
    modes: { g: 'من ميلادي إلى هجري', h: 'من هجري إلى ميلادي' },
    day: 'اليوم',
    month: 'الشهر',
    year: 'السنة',
    today: 'تاريخ اليوم',
    hijriLabel: 'هجري',
    gregorianLabel: 'ميلادي',
    weekdayLabel: 'اليوم من الأسبوع',
    suffixHijri: 'هـ',
    suffixGregorian: 'م',
    copyResult: 'انسخ التاريخ',
    equals: 'الموافق',
    errors: {
      invalid: 'هذا التاريخ غير موجود. راجع اليوم والشهر.',
      range: 'التواريخ المدعومة من 1901 إلى 2076 (من نحو 1318 إلى 1499 هـ).',
      unsupported: 'هذا المتصفح لا يتضمن تقويم أم القرى، فلا يستطيع تحويل التواريخ.',
      day30: 'هذا الشهر الهجري 29 يوماً.',
    },
    moon: {
      title: 'القمر في ذلك اليوم',
      illuminated: 'مضاء',
      approximate: 'محسوب من متوسط الدورة القمرية. قد يبعد القمر الفعلي عن هذا الحساب حتى نصف يوم.',
      phases: {
        new: 'محاق',
        waxingCrescent: 'هلال متزايد',
        firstQuarter: 'تربيع أول',
        waxingGibbous: 'أحدب متزايد',
        full: 'بدر',
        waningGibbous: 'أحدب متناقص',
        lastQuarter: 'تربيع أخير',
        waningCrescent: 'هلال متناقص',
      },
    },
    calendar: {
      title: 'الشهر في نظرة',
      days: 'يوماً',
      weekdays: ['أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'سبت'],
      pick: 'افتح هذا اليوم',
    },
    approximate:
      'التواريخ بحسب تقويم أم القرى، وهو محسوب مسبقاً. قد يبدأ الشهر قبل يوم أو بعده في البلدان التي تعتمد رؤية الهلال، فارجع إلى الجهة المختصة في بلدك للمناسبات الدينية.',
    steps: [
      'اختر الاتجاه: من ميلادي إلى هجري، أو من هجري إلى ميلادي.',
      'اكتب اليوم والشهر والسنة، أو اضغط «تاريخ اليوم».',
      'اقرأ التاريخ المحوّل واليوم والقمر، أو اضغط يوماً في تقويم الشهر لتنتقل إليه.',
    ],
    faq: [
      {
        q: 'أي تقويم هجري يستخدم؟',
        a: 'تقويم أم القرى المضمّن في متصفحك. وهو التقويم المعتمد رسمياً في السعودية، ويُحسب مسبقاً ولا يعتمد الرؤية.',
      },
      {
        q: 'لماذا قد يختلف التاريخ بيوم عن بلدي؟',
        a: 'بعض الدول تبدأ الشهر عند رؤية الهلال، وقد يسبق ذلك التاريخ المحسوب بيوم أو يتأخر عنه. وللمناسبات الدينية مثل رمضان والعيدين اتبع إعلان الجهة المختصة في بلدك.',
      },
      {
        q: 'ما السنوات التي يمكن تحويلها؟',
        a: 'من 1901 إلى 2076 ميلادي، أي من نحو 1318 إلى 1499 هجري. وهذه هي السنوات التي يغطيها تقويم أم القرى في المتصفحات.',
      },
      {
        q: 'كيف يُحسب القمر؟',
        a: 'من متوسط طول الشهر القمري، محسوباً من محاق معروف. هو تقدير قريب يكفي للصورة واسم الطور، لكن المحاق والبدر الفعليين قد يختلفان عنه حتى نصف يوم.',
      },
      {
        q: 'هل يُخزَّن أو يُرسَل شيء؟',
        a: 'لا. يجري التحويل في متصفحك ولا يُرسل ما تكتبه إلى أي مكان.',
      },
    ],
    cta: {
      title: 'تبني لجمهور عربي؟',
      text: 'نبني مواقع وتطبيقات عربية أولاً، باتجاه من اليمين إلى اليسار وتواريخ هجرية ومحتوى ثنائي اللغة منفّذ بشكل صحيح من البداية.',
      button: 'تعرّف على الحلول الرقمية',
    },
  },

  schema: {
    h1: 'مولّد البيانات المنظمة',
    subtitle: 'املأ النموذج واحصل على JSON-LD لشركتك أو متجرك أو مقالك أو أسئلتك، مع فحص أثناء الكتابة.',
    typeLabel: 'لأي شيء هذه البيانات؟',
    types: {
      Organization: 'شركة',
      LocalBusiness: 'نشاط محلي',
      FAQPage: 'أسئلة شائعة',
      Article: 'مقال',
    },
    fields: {
      name: 'الاسم',
      url: 'عنوان الموقع',
      logo: 'عنوان الشعار',
      email: 'البريد الإلكتروني',
      telephone: 'الهاتف',
      sameAs: 'حسابات أخرى',
      image: 'عنوان الصورة',
      street: 'الشارع',
      city: 'المدينة',
      region: 'المنطقة',
      postalCode: 'الرمز البريدي',
      country: 'رمز الدولة',
      hours: 'ساعات العمل',
      priceRange: 'فئة الأسعار',
      headline: 'العنوان',
      author: 'الكاتب',
      datePublished: 'تاريخ النشر',
      dateModified: 'تاريخ التعديل',
      publisher: 'الناشر',
    },
    hints: {
      sameAs: 'عنوان واحد في كل سطر: حسابات التواصل، صفحة ويكيبيديا.',
      country: 'حرفان مثل SA أو AE أو EG.',
      hours: 'مثل Mo-Fr 09:00-17:00.',
      priceRange: 'مثل $$.',
      datePublished: 'سنة-شهر-يوم: 2026-01-15.',
      dateModified: 'سنة-شهر-يوم: 2026-01-15.',
      headline: 'الإرشاد الشائع: حتى 110 أحرف.',
    },
    faqQuestion: 'السؤال',
    faqAnswer: 'الإجابة',
    faqItem: 'السؤال {n}',
    addQuestion: 'أضف سؤالاً',
    removeQuestion: 'احذف السؤال {n}',
    loadExample: 'املأ بمثال',
    clear: 'امسح',
    output: 'الكود الجاهز للصق',
    copyCode: 'انسخ الكود',
    readiness: 'الحقول المطلوبة',
    checklist: 'الفحوص',
    status: {
      ok: 'سليم',
      missing: 'ناقص',
      invalid: 'يحتاج تصحيحاً',
      long: 'طويل',
    },
    levels: { required: 'مطلوب', recommended: 'موصى به', optional: 'اختياري' },
    problems: {
      invalid: 'هذه القيمة لا تبدو صحيحة.',
      long: 'أطول من الحد الشائع، فقد يُقتطع.',
      faqPair: 'املأ السؤال والإجابة معاً.',
      faqMissing: 'أضف سؤالاً واحداً على الأقل مع إجابته.',
    },
    tryGoogle: 'اختبره بأداة النتائج المميزة من جوجل',
    placeUse: 'الصقه في head أو body الصفحة التي يصفها.',
    notice:
      'النتيجة الجيدة هنا تعني أن البيانات مكتملة، ولا تعني أن جوجل سيعرض نتيجة مميزة. ويجب أن يطابق النص ما هو ظاهر في الصفحة.',
    steps: [
      'اختر لأي شيء هذه البيانات: شركة أو نشاط محلي أو أسئلة شائعة أو مقال.',
      'املأ الحقول. تُظهر الفحوص على الجانب ما هو ناقص أو يحتاج إلى تصحيح.',
      'انسخ الكود والصقه في الصفحة التي يصفها، ثم اختبره بأداة النتائج المميزة من جوجل.',
    ],
    faq: [
      {
        q: 'ما هو JSON-LD؟',
        a: 'هو كتلة بيانات توضع في الصفحة وتخبر محركات البحث بصيغة ثابتة عمّا تتحدث الصفحة، مثل اسم النشاط وعنوانه وساعات عمله. ولا يراها الزوار.',
      },
      {
        q: 'هل سأحصل على نتائج مميزة في جوجل؟',
        a: 'ليس بمجرده. البيانات الصحيحة تجعل الصفحة مؤهلة لبعض أنواع النتائج المميزة، لكن جوجل هو من يقرر عرضها. ولا يغيّر شيء هنا ترتيبك مباشرة.',
      },
      {
        q: 'أين أضع الكود؟',
        a: 'داخل الصفحة التي يصفها، في head أو في body. وفي أغلب منشئات المواقع يوجد مكان للكود المخصص أو حقل لسكربتات الرأس.',
      },
      {
        q: 'لماذا يجب أن يطابق النص الصفحة؟',
        a: 'تطلب جوجل أن تصف البيانات المنظمة ما يراه الزوار فعلاً. والبيانات عن أسئلة أو تفاصيل غير موجودة في الصفحة قد تُتجاهل أو تُعد مخالفة لإرشاداتها.',
      },
      {
        q: 'هل يُخزَّن أو يُرسَل شيء؟',
        a: 'لا. يُبنى الكود في متصفحك ولا يُرسل ما تكتبه إلى أي مكان. ورابط الاختبار يفتح أداة جوجل في تبويب جديد فقط.',
      },
    ],
    cta: {
      title: 'البيانات المنظمة جزء واحد من السيو التقني',
      text: 'ننفّذها على مواقع كاملة بالأنواع المناسبة لكل صفحة، مع وسوم canonical وhreflang وخرائط الموقع والعرض القابل للزحف.',
      button: 'تعرّف على خدمات السيو',
    },
  },

  brief: {
    h1: 'كاتب موجز المشروع',
    subtitle: 'أجب عن بضعة أسئلة واحصل على موجز واضح ترسله لأي شركة أو مستقل.',
    fields: {
      name: 'اسم المشروع أو الشركة',
      type: 'ماذا تحتاج؟',
      goal: 'ماذا يجب أن يحقق؟',
      audience: 'لمن هو؟',
      budget: 'نطاق الميزانية',
      timeline: 'متى تحتاجه؟',
      features: 'ما الذي يجب أن يتضمنه؟',
      references: 'مواقع أو تطبيقات تعجبك',
      notes: 'أي شيء آخر',
    },
    placeholders: {
      name: 'عطور دانة',
      goal: 'مضاعفة مبيعاتنا عبر الإنترنت خلال ستة أشهر.',
      audience: 'نساء من 25 إلى 45 سنة في السعودية والإمارات.',
      references: 'example.com, another-example.com',
      notes: 'قيود، أنظمة قائمة، أشخاص يجب أن يوافقوا.',
    },
    hints: {
      goal: 'نتيجة واحدة واضحة أفضل من قائمة أمنيات.',
      references: 'افصل بفواصل أو بأسطر جديدة.',
    },
    types: {
      website: 'موقع تعريفي للشركة',
      store: 'متجر إلكتروني',
      app: 'تطبيق جوال',
      ads: 'حملة إعلانية',
      brand: 'هوية بصرية',
      seo: 'تحسين محركات البحث',
      other: 'شيء آخر',
    },
    budgets: {
      b1: 'أقل من 3,000 دولار',
      b2: 'من 3,000 إلى 10,000 دولار',
      b3: 'من 10,000 إلى 30,000 دولار',
      b4: 'أكثر من 30,000 دولار',
      undecided: 'لم أحدد بعد',
    },
    timelines: {
      t1: 'خلال شهر',
      t2: 'من شهر إلى 3 أشهر',
      t3: 'أكثر من 3 أشهر',
      flexible: 'مرن',
    },
    features: {
      bilingual: 'عربي وإنجليزي',
      payments: 'دفع إلكتروني',
      booking: 'حجوزات',
      dashboard: 'لوحة تحكم للإدارة',
      integrations: 'ربط مع أنظمة أخرى',
      analytics: 'تحليلات وتتبع',
      content: 'كتابة محتوى',
      seo: 'تحسين لمحركات البحث',
    },
    document: {
      documentTitle: 'موجز مشروع',
      openQuestions: 'ما زال يحتاج قراراً',
      sections: {
        type: 'المطلوب',
        goal: 'الهدف',
        audience: 'الجمهور',
        budget: 'الميزانية',
        timeline: 'الموعد',
        features: 'يجب أن يتضمن',
        references: 'مراجع',
        notes: 'ملاحظات',
      },
      placeholderTitle: 'مشروعك',
      empty: 'بانتظار إجابتك',
    },
    progress: 'اكتمال الموجز',
    progressDone: 'جاهز للإرسال',
    copy: 'انسخ الموجز',
    download: 'نزّله كملف نصي',
    sendToUs: 'انسخه وافتح نموذج التواصل',
    sendHint: 'الصقه في وصف المشروع داخل النموذج.',
    fileName: 'project-brief.txt',
    steps: [
      'أجب عن الأسئلة على الجانب. يُكتب الموجز بجوارها وأنت تكتب.',
      'املأ الأقسام الستة الأساسية. وما تتركه فارغاً يُذكر في النهاية كأسئلة تحتاج قراراً.',
      'انسخ الموجز أو نزّله كملف نصي وأرسله لمن تريد منهم عرض سعر.',
    ],
    faq: [
      {
        q: 'لماذا أكتب موجزاً أصلاً؟',
        a: 'الموجز الواضح يجعل عروض الأسعار التي تصلك تصف العمل نفسه، فتستطيع مقارنتها. ويوفّر أيضاً مكالمة أولى كانت ستذهب في طرح هذه الأسئلة.',
      },
      {
        q: 'هل يجب أن أعرف الميزانية؟',
        a: 'لا. اختر «لم أحدد بعد» وسيذكر الموجز ذلك. لكن ذكر نطاق عادةً يجلب عروضاً أكثر واقعية من تركه فارغاً.',
      },
      {
        q: 'هل أستطيع استخدام الموجز مع شركات أخرى؟',
        a: 'نعم. هو نص عادي وملك لك. أرسله لمن تشاء.',
      },
      {
        q: 'ماذا أفعل بقائمة «ما زال يحتاج قراراً»؟',
        a: 'هذه أسئلة أساسية تركتها فارغة. الشركة الجيدة ستسألها على أي حال، والإجابة عنها مبكراً تسرّع عرض السعر.',
      },
      {
        q: 'هل يُخزَّن أو يُرسَل شيء؟',
        a: 'لا. يُكتب الموجز في متصفحك ولا يُرسل ما تكتبه إلى أي مكان. ولا يغادر جهازك إلا عندما تنسخه أو تنزّله أو تلصقه أنت في مكان ما.',
      },
    ],
    cta: {
      title: 'تريد أن نراجع موجزك؟',
      text: 'أرسله عبر نموذج التواصل. نرد بأسئلة وبأسلوب عمل ونطاق واقعي، لا بعرض سعر جاهز.',
      button: 'تعرّف على الحلول الرقمية',
    },
  },
};

export const batch2Content = { en, ar };
