/**
 * Service Worker for Rumuze PWA
 * Using Workbox v7
 * 
 * Features:
 * - Pre-caching of critical assets
 * - StaleWhileRevalidate for JS/CSS
 * - CacheFirst for Images/Fonts
 * - NetworkFirst for API
 * - Offline Fallback
 * - Background Sync for Forms
 */

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute, setCatchHandler } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Claim control immediately
self.skipWaiting();
clientsClaim();

// 1. Pre-cache & Route
// This loads the manifest generated by Vite-PWA plugin
// Includes: index.html, core js bundles, critical css, fonts
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// 2. Navigation Fallback
// If a navigation route fails (offline), serve index.html (SPA shell)
// This ensures the App shell loads, and then client-side routing takes over
const allowlist = [/^\/$/];
const denyList = [
  /^\/api\//,     // API calls
  /^\/admin\//,   // Admin routes
  /\.[a-z]+$/i    // Files with extensions
];
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('/index.html'), { allowlist, denyList })
);

// 3. Runtime Caching Strategies

// JS & CSS Bundles (Stale-While-Revalidate)
// Serve cache instantly, update in background
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Images (Cache First)
// Store images for a long time. They rarely change.
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 Days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200], // Cache opaque responses (e.g. Unsplash)
      }),
    ],
  })
);

// Fonts (Cache First)
// Critical for FCP/LCP.
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 Year
      }),
    ],
  })
);

// API Calls (Network First)
// Try network, fallback to cache if offline.
// Good for GET requests like blog posts, portfolio items.
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') || url.hostname === 'api.rumuze.com',
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 3, // Fallback to cache after 3s
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 Hours
      }),
    ],
  })
);

// 4. Background Sync (Contact Form)
// Queue failed POST requests and retry them when back online
const bgSyncPlugin = new BackgroundSyncPlugin('contactQueue', {
  maxRetentionTime: 24 * 60, // Retry for 24 hours
});

registerRoute(
  ({ url }) => url.pathname.includes('/api/contact'),
  new NetworkFirst({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

// 5. Global Offline Fallback (Comprehensive)
// If everything fails (network + cache miss), serve a custom offline page or placeholder
setCatchHandler(async ({ event }) => {
  switch (event.request.destination) {
    case 'document':
      // If navigation fails, try serving the offline.html page from cache
      // Note: offline.html must be pre-cached or added during install
      return caches.match('/offline.html');

    case 'image':
      // Return a placeholder SVG or image
      return new Response(
        '<svg role="img" aria-labelledby="offline-title" viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg"><title id="offline-title">Offline</title><rect width="100%" height="100%" fill="#f0f0f0"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="24px" fill="#888">Offline</text></svg>',
        { headers: { 'Content-Type': 'image/svg+xml' } }
      );

    default:
      return Response.error();
  }
});

// Install Event: Cache custom offline page manualy if not in manifest
self.addEventListener('install', (event) => {
  const offlinePage = '/offline.html';
  event.waitUntil(
    caches.open('offline-fallback').then((cache) => cache.add(offlinePage))
  );
});
