import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Background Sync for Contact Form
const bgSyncPlugin = new BackgroundSyncPlugin('contactFormQueue', {
    maxRetentionTime: 24 * 60 // Retry for max of 24 Hours
});

registerRoute(
    ({ url }) => url.pathname.includes('/api/contact') || url.pathname.includes('/submit-form'),
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'POST'
);

// Offline Fallback for Navigation
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
    denylist: [/\/[^/]+\.[^/]+$/], // Ignore files with extensions
});
registerRoute(navigationRoute);

// Catch-all for offline navigation fallback to branded page
// Note: In a SPA, the above NavigationRoute usually handles it by serving index.html
// However, if we want a specific "Offline" route:
/*
registerRoute(
  ({ event }) => event.request.mode === 'navigate',
  async () => {
    try {
      return await handler();
    } catch (error) {
      return caches.match('/offline');
    }
  }
);
*/

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
