/**
 * Service Worker for Rumuze PWA
 * Using Workbox v7
 * 
 * Features:
 * - Pre-caching of critical assets
 * - StaleWhileRevalidate for JS/CSS
 * - CacheFirst for Images/Fonts
 * - NetworkFirst for API
 * - Offline Fallback
 * - Background Sync for Forms
 */

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute, setCatchHandler } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Claim control immediately
self.skipWaiting();
clientsClaim();

// 1. Pre-cache & Route
// This loads the manifest generated by Vite-PWA plugin
// Includes: index.html, core js bundles, critical css, fonts
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// 2. Navigation Fallback
// If a navigation route fails (offline), serve index.html (SPA shell)
// This ensures the App shell loads, and then client-side routing takes over
// FIXED: Removed restrictive allowlist - now matches ALL navigation routes for full SPA support
const denyList = [
  /^\/api\//,     // API calls
  /^\/admin\//,   // Admin routes
  /\.[a-z]+$/i    // Files with extensions (assets)
];
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('/index.html'), { denyList })
);

// 3. Runtime Caching Strategies

// JS & CSS Bundles (Stale-While-Revalidate)
// Serve cache instantly, update in background
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Images (Cache First) - WITH SIZE LIMITS
// OPTIMIZED: Limit to 50 images, auto-purge on quota error
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,               // LIMIT: Max 50 images
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
        purgeOnQuotaError: true,      // Auto-delete if storage full
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Fonts (Cache First)
// Critical for FCP/LCP.
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 Year
      }),
    ],
  })
);

// API Calls (Network First)
// Try network, fallback to cache if offline.
// Good for GET requests like blog posts, portfolio items.
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') || url.hostname === 'api.rumuze.com',
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 3, // Fallback to cache after 3s
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 Hours
      }),
    ],
  })
);

// 4. Background Sync (Contact Form)
// Queue failed POST requests and retry them when back online
// OPTIMIZED: Added unique key strategy to prevent duplicate submissions
const bgSyncPlugin = new BackgroundSyncPlugin('contactQueue', {
  maxRetentionTime: 24 * 60, // Retry for 24 hours
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        // Clone request with unique submission ID to prevent duplicates
        const request = entry.request.clone();
        const formData = await request.clone().formData();

        // Add unique submission ID if not present
        if (!formData.has('_submissionId')) {
          const uniqueId = `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
          formData.append('_submissionId', uniqueId);
        }

        await fetch(request);
      } catch (error) {
        // Re-queue failed request
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  },
});

registerRoute(
  ({ url }) => url.pathname.includes('/api/contact'),
  new NetworkFirst({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

// 5. Global Offline Fallback (Comprehensive)
// If everything fails (network + cache miss), serve a custom offline page or placeholder
setCatchHandler(async ({ event }) => {
  switch (event.request.destination) {
    case 'document':
      // If navigation fails, try serving the offline.html page from cache
      // Note: offline.html must be pre-cached or added during install
      return caches.match('/offline.html');

    case 'image':
      // Return a placeholder SVG or image
      return new Response(
        '<svg role="img" aria-labelledby="offline-title" viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg"><title id="offline-title">Offline</title><rect width="100%" height="100%" fill="#f0f0f0"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="24px" fill="#888">Offline</text></svg>',
        { headers: { 'Content-Type': 'image/svg+xml' } }
      );

    default:
      return Response.error();
  }
});

// Install Event: Cache custom offline page manualy if not in manifest
self.addEventListener('install', (event) => {
  const offlinePage = '/offline.html';
  event.waitUntil(
    caches.open('offline-fallback').then((cache) => cache.add(offlinePage))
  );
});
